# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kleio < Formula
  desc "Kleio CLI — capture work discovered during development"
  homepage "https://github.com/kleio-build/kleio-cli"
  version "0.0.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kleio-build/kleio-cli/releases/download/v0.0.11/kleio_0.0.11_darwin_x86_64.tar.gz"
      sha256 "48063cc83be544f8b92a209eecd269db6ce1ab478ad5a8dd1e50e4a84f26b235"

      define_method(:install) do
        bin.install "kleio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kleio-build/kleio-cli/releases/download/v0.0.11/kleio_0.0.11_darwin_arm64.tar.gz"
      sha256 "b1adc87b09793ad734b7d3fbfb220fc3ffee71b5fd70f127c9d2d221e961f3c7"

      define_method(:install) do
        bin.install "kleio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kleio-build/kleio-cli/releases/download/v0.0.11/kleio_0.0.11_linux_x86_64.tar.gz"
      sha256 "837482d7292b61889729c4de155a9c7a5b907f06a6ab6abfb1968e3ab3b3af66"
      define_method(:install) do
        bin.install "kleio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kleio-build/kleio-cli/releases/download/v0.0.11/kleio_0.0.11_linux_arm64.tar.gz"
      sha256 "5fa549490599ec99b625912ce2843e14215057ebe7a8a7c9387c0236ce5c68bb"
      define_method(:install) do
        bin.install "kleio"
      end
    end
  end

  test do
    system "#{bin}/kleio", "--version"
  end
end
