# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kleio < Formula
  desc "Kleio CLI — capture work discovered during development"
  homepage "https://github.com/kleio-build/kleio-cli"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kleio-build/kleio-cli/releases/download/v0.0.2/kleio_0.0.2_darwin_x86_64.tar.gz"
      sha256 "9ed30d6411db6e418cb4687079b2b4f98eb9614cf47ad4a50199a52762b3dab3"

      define_method(:install) do
        bin.install "kleio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kleio-build/kleio-cli/releases/download/v0.0.2/kleio_0.0.2_darwin_arm64.tar.gz"
      sha256 "93c7ede05abcd0868ed5100205f795474ba0b579f220a993fa008f12f9c95fbc"

      define_method(:install) do
        bin.install "kleio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kleio-build/kleio-cli/releases/download/v0.0.2/kleio_0.0.2_linux_x86_64.tar.gz"
      sha256 "6891b8e9c1cde03605e1b2352260ef097f10570154a20d79afabbb91b783ca89"
      define_method(:install) do
        bin.install "kleio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kleio-build/kleio-cli/releases/download/v0.0.2/kleio_0.0.2_linux_arm64.tar.gz"
      sha256 "f832c2a6a82c7a16b56c7b66e35fdcdbcaab5bfe5c37d705b2475f5f697e9cd1"
      define_method(:install) do
        bin.install "kleio"
      end
    end
  end

  test do
    system "#{bin}/kleio", "--version"
  end
end
